### ISSUE TITLE
有些视频需要密码，无法看

### ISSUE THREAD

**Issue by tanhaipeng** [ThinkDevelopers/PHPConChina#4]
RT，能否公开演讲视频呢，让没能去现场的也学习学习，thanks

**Comment by star001007** [comment]
mark

**Comment by daydaygo** [comment]
@tanhaipeng 2016视频已经有的, 放在优酷上面, 和往期一样; 另外 2016 有2场 php 大会, 内容大部分不一样, 可以去看看
