### ISSUE TITLE
phpcon2018 pdf文件有部分文件不完整

### ISSUE THREAD

**Issue by iceHeartLuo** [ThinkDevelopers/PHPConChina#7]
2018里的《微博跨语言服务化_周晶_PHPCON2018.pdf》只有3.2M，请查看下，谢谢

https://github.com/ThinkDevelopers/PHPConChina/blob/master/PHPCON2018/%E5%BE%AE%E5%8D%9A%E8%B7%A8%E8%AF%AD%E8%A8%80%E6%9C%8D%E5%8A%A1%E5%8C%96_%E5%91%A8%E6%99%B6_PHPCON2018.pdf

**Comment by bobxia** [comment]
格式有点问题，等空了研究下什么情况

**Comment by bobxia** [comment]
已经好了
